### PR TITLE
Added support for new data type..

### PR DESCRIPTION
**Pull request by bugyboo**
Hi,
Could you please look at these changes on new data type when you have time.

Tell me what you think.

Thanks,,

### CODE REVIEW

**Comment by sai-pullabhotla** [comment]
@bugyboo - thanks for the contribution. Brief review of the code looks good to me. From what I see, this commit supports Map with String keys and String values. Is that sufficient? Would there be cases where other types (especially for values) need to be supported, either primitive or complex objects? Would you provide me your particular use case/requirements so I can think through it? I do plan to add support for Embedded Entities, but want to make sure all/most scenarios are covered.

**Comment by bugyboo** [comment]
@sai-pullabhotla Thanks for your feedback.
I love Catatumbo for its speed and easy to use and I can't imagine how good it is if we have support for a map that supports all Catatumbo's data types on its values even `Entity` objects would be great.

I'm  sure you have a plan to support embedded entities in a good way like always and I just wanted to point out this approach as an alternative.

**Comment by sai-pullabhotla** [comment]
Thanks. I would still like to understand the purpose of using Maps in your entities. Is it to allow the end users of your Application to add custom fields? If we embed the Maps as Embedded JSON Entities, they would not be searchable. Is that acceptable?

**Comment by bugyboo** [comment]
@sai-pullabhotla 
Yes,  this is one of the use cases.  Also,  just for the simplisty to persist. 
The simple map that I use now is Searchable for ex.  `SELECT * FROM Entity WHERE Entity.propertyname CONTAINS @1` 
I'm guessing because when embedded entity doesn't have a key it can be searched.

**Comment by sai-pullabhotla** [comment]
What exactly were you passing for @1 (the parameter)? Are you able to search for things like if favorite color is RED?

**Comment by bugyboo** [comment]
@sai-pullabhotla 
it's only working if the map key value doesn't have spaces.
the correct query would be something like this 

`SELECT * FROM MapObject WHERE properties.favorite_color = "RED"`

**Comment by sai-pullabhotla** [comment]
@bugyboo - Thanks. I've another question. What is the reason for adding new methods to the `DatastoreKey`(e.g. `getName()`, `getParent()`)? The interface already has `name()` and `parent()` methods. 

Thanks.

**Comment by sai-pullabhotla** [comment]
@bugyboo - I've enhanced your patch a little bit and implemented the support for Maps. Check it out at https://github.com/sai-pullabhotla/catatumbo/issues/34. I will be cutting a release either tonight or tomorrow night. Feedback is welcome. Thanks again for your contribution.

**Comment by bugyboo** [comment]
@sai-pullabhotla 
absolutely very good work Sai 👍

**Comment by sai-pullabhotla** [comment]
Implemented a slight variation of this, so closing this request.

**Pull request closed without merging**
