### PR TITLE
#49 Implementation of support for Immutable entities

### PR DESCRIPTION
**Pull request by athieriot**
This introduce a new annotation called @EntityConstructor that will
identify an entity as Immutable. Meaning that there won't be the needs for
Setters or Default Constructor anymore.

Instead, the annotation constructor will need to have enough parameters
to support all fields. Each parameter needs to be annotated with
@Property to identity its name.

The only potential backward compatible problem comes from here: https://github.com/sai-pullabhotla/catatumbo/compare/master...athieriot:immutable?expand=1#diff-cb134f856e994b7bb0cefe33fd63d5ccR536
Previously, for `exploded embedded entities`, the original object was modified to set the field to an instantiated, nullified version.
Obviously, for immutable entities that won't do so I stopped this behaviour. This needed some change in the `equals` and `equalsExpectId` methods in the unit tests.
If it's an issue, I can reintroduce it for mutable entities only.

The main refactor concerned the `Unmarshaller` class where all the calls to setters needed to be in one place.

Finally, I know that the format don't look quite right. I'll see what I can do about it.

### CODE REVIEW

**Comment by bnordli** [comment]
This looks like a very nice feature!

Just a couple of suggestions: 

* Reusing the @Property annotation is not so good. For instance the 'name' property (when supplied in the constructor) -- does it refer to the (Java) field name or the (Datastore) property name. (I assume the first, but then the documentation of @Property isn't correct anymore.) Also, the 'optional' or 'indexed' property don't make much sense. (I don't have a good suggestion for a new name for the annotation, but I think the two should be separated.)

* Also, the @Property annotation of constructor parameters should be optional when the parameter name is available (compiled with -parameters) and matches the field name. With this, a lot of boiler-plate can be removed, since in the vast majority of cases, these should match.

**Comment by sai-pullabhotla** [comment]
+1 for the comments from @bnordli 
Here are a couple of questions/thoughts: 

* Rename `EntityConstructor` annotation to `PersistenceConstructor` so it is more generic and can be applied to root entities as well as Embeddables. 
* The `PersistenceConstructor` annotation optionally takes an array of Strings that refer to the names of instance variables. When not specified, code must be compiled with -parameters option, in which case, each parameter name will be matched with the corresponding instance variable. If we don't like the array of Strings option, we can add a new annotation `@FieldRef` that can be specified on each parameter. 

```
public class Point {
  private final int x;
  private final int y;

  @PersistenceConstructor
  public Point(int x, int y) {
    this.x = x;
    this.y = y;
  }
  //getX
  //getY
}

```

```
public class Point {
  private final int x;
  private final int y;

  @PersistenceConstructor({"x", "y"})
  public Point(int x, int y) {
    this.x = x;
    this.y = y;
  }
  //getX
  //getY
}

```

```
public class Point {
  private final int x;
  private final int y;

  @PersistenceConstructor
  public Point(@FieldRef("x") int x, @FieldRef("y") int y) {
    this.x = x;
    this.y = y;
  }
  //getX
  //getY
}

```


* One question/concern I've is - do we really need to support multiple constructors for a given domain object (for the framework's use)? I'm thinking we should restrict to a single PersitenceConstructor for a given class. This eliminates the overhead of finding the correct constructor when entities are unmarshalled. 
* Finally, I think it would be nice to support partial immutable entities (entities with some fields mutable and some immutable). This may not be *just* for immutability, but to make sure an object's state is always valid. For example, cannot have an EmailAddress object without the email, but name is optional. What do you think?

**Comment by athieriot** [comment]
Thank you for your reviews!

I have made some of the requested changes, mainly:

- Rename EntityConstructor to PersistenceConstructor
- Use a new FieldRef annotation instead of the existing Property
- Use the original parameter name if class compiled with -parameters (Not sure how to test both cases for that one though)
- Allow only one PersistenceConstructor

I kept from doing the last point for now (partial immutable entities) as I thought it would be a bit more involved. However I am happy to look into it, in a subsequent Pull Request maybe?

In the meantime, tell me what you think of the latest commit

**Comment by sai-pullabhotla** [comment]
@athieriot, @bnordli 
Sorry it took a while to respond. This is great work and works as expected, however I've a couple of concerns: 

- This code will have issue when some properties are marked as optional 
- When entities change down the road (e.g. add a couple of fields), existing data would fail to map back 

Of course, both may be solved by reverting the code to your first PR that supports multiple Persistence Constructors. But again, the number of constructors and the number of parameters in each constructor could get ugly very easily, especially when entities have many fields. 

I'm wondering if we should rather support and recommend the use of **Builder** pattern instead of constructors approach, which also solves the immutability/consistent state problem. Doing some research on the web, it seems more and more developers are choosing the Builder pattern for this very same purpose. 

In essence, this would work as outlined below, when a persistence class does not have a default public constructor: 

- Check the entity/persistence class for existence of a static newBuilder method, if so, invoke it. 
- On the returned Builder object, for each field in the entity/persistence class, call the setField method, which is same as we do today
- Once all fields are set, call the build method on the Builder. 

Of course, more details need to be ironed out before proceeding this path. 

Let me know your thoughts.

**Comment by athieriot** [comment]
After discussing this with a few colleagues, leveraging the builder pattern seems a much cleaner implementation. I am fully committed to follow your recommendations and make the appropriate updates.

I am personally just concerned about forcing users to use one specific form of Immutable entities (For which conventions can be more freely interpreted and assumptions can be wrongly made).

More specifically, I'm thinking about this: A good alternative to a strict builder pattern is to use chain-able "setters" on the entity itself, like `withField(value)`. Each of those return a fresh instance of the entity with the specified field allocated. (And avoid the need of a Builder object)
Is it realistic to want to support this as well?

In the same line of questions:
- Should we support the builder pattern on top of `@PersistenceConstructor`?
- Should we expect specific method names (`set<Field>`) or simply allow to annote them if it's different (Same question for the newBuilder)?
- Does this open the need to support framework such as Lombok (And probably others)?

I think that, all in all, I agree with the fact that a Constructor might be a bit flaky over time. I guess I am just unsure about the actual format we should expect from user's entities.

I can give that idea a go in the next few days, see how it goes. In the meantime it would be good, indeed, to have other developers opinions to try to discover the preferred way.

**Comment by bnordli** [comment]
I fail to see the problem with optional fields, or with new fields breaking existing data: If the constructor has an argument that is not found in the data, Catatumbo should just provide the default value (null or 0).

I strongly prefer the builder pattern over `with...` methods, because the latter will construct very many unnecessary objects, and they are more cumbersome to write.

I think both of `@PersistenceConstructor` and the Builder pattern are good solutions, and I think it is reasonable if both are supported.

**Comment by sai-pullabhotla** [comment]
Here are my thoughts on the builder pattern: 

- We force PersistenceClass.newBuilder - should be okay even for existing code, just a new method, if they don't have one. Existing non-standard method can be deprecated. 
- For the Builder mutation methods, we could check for any of the common patterns in the below order. If there is existing code that does not have methods with the below pattern, they need to add needed methods and probably depreciate the existing methods. The look up for the setter method is only done one time during the entity introspection, so marshalling/unmarshalling should perform the way they are. 
  - setField - seems to be the new standard? 
  - withField - widely used 
  - field - widely used
- finally, we force the builder.build method that returns an instance of PersistenceClass. 
- Builders can use the chaining pattern to return the builder or can return void. Framework does not enforce/depend on the return type. 
- Builders may include getField methods, if needed, but framework does not require/use them 

Let me know what you think. Thanks.

**Comment by sai-pullabhotla** [comment]
@athieriot @bnordli - 

Attached is a patch to support Builder Pattern (as outlined previously). I still have to do more tests/cleanup/document, but am pretty close. When you get a chance try it out and let me know of any comments/suggestions. The patch is built from the HEAD in Eclipse format. 

[catatumbo5.txt](https://github.com/sai-pullabhotla/catatumbo/files/1286622/catatumbo5.txt)

**Comment by athieriot** [comment]
Hi @sai-pullabhotla 

This is looking very good, thanks.
I was starting on the same work on my side but it's probably better if it's you ;)

I like the Strategy Pattern better than my own implementation as it would allow more use cases if need be. (Like do you think it's worth bringing the immutable Constructor back in there at some point?)

The only thing for me is that I was kind of hopping to be able to use method (with...) that would return the current instance. Allowing the implementation not to have to store any state (Returning a new instance each time) and maybe avoid writing a new Builder for every single entity.
The way it's done in the patch, there is no way it's going to happen.

It look like a solid way of doing it anyway so don't hesitate to go for it or create a PR if you want a bit more reviews.

Thanks !

**Comment by athieriot** [comment]
Just tested on our project using an inner class for the Builder and it's working perfectly :)

**Comment by sai-pullabhotla** [comment]
@athieriot 

> do you think it's worth bringing the immutable Constructor back in there at some point?

Not sure. I'm concerned that constructors could get your code really ugly when working on large entities. They are fine for smaller entities with up to a handful of parameters. In my opinion, we are trying to solve/address two issues: 

 - Support for Immutable objects 
 - Make sure persistence objects are in a valid state (e.g. inter dependent fields - joinDate should be less than terminationDate). 

Builder pattern solves both while keeping your code more cleaner. Providing multiple options for doing the same thing makes sense if new approach is better over the older. Right now, the API does not have a way to do this, so it is better to provide a single option that is best. We need to make a call on that to decide one way or the other. 

> The only thing for me is that I was kind of hopping to be able to use method (with...) that would return the current instance. Allowing the implementation not to have to store any state (Returning a new instance each time) and maybe avoid writing a new Builder for every single entity.
> The way it's done in the patch, there is no way it's going to happen.
> 

I don't quite follow what you are saying. Would you please elaborate/explain with a simple example, so we are on the same page?

**Comment by athieriot** [comment]
So, here is an example of what we are doing right now:

```
public class Document {
    private final Content content;
    private String _id;
}

public Document(Content content) {
    this.content = content;
}

 public Document withId(String id) {
    Document newDoc = new Document(content);
    newDoc._id = id;
    return newDoc;
}
```
I'm sure there is several other way to implement this but, basically, each `withThing` call only returns a new instance and nothing else (Doesn't really store the value in a state).
From a Catatumbo point of view it would mean keeping track of those instances and call each next method in the chain on it instead.

This approach obviously creates many more instances but avoid the need for a builder for each and every single Entity (Including embedded ones)

Does that make sense?

**Comment by sai-pullabhotla** [comment]
Not sure if we can ever support this specific case, but if it helps, you can in fact use Lombok/Kotlin (tools that process compile time annotations) to convert existing model classes to one of the patterns (classic JavaBeans or Builder). I just tested with Lombok's Builder and everything works fine. Below is an example with Lombok's Builder. I plan to merge the support for Builder pattern and cut a release by EOW, unless you thnink I should hold off for any reason. 

import com.jmethods.catatumbo.Entity;
import com.jmethods.catatumbo.EntityManager;
import com.jmethods.catatumbo.EntityManagerFactory;
import com.jmethods.catatumbo.Identifier;

import lombok.Builder;
import lombok.Data;

```
import com.jmethods.catatumbo.Entity;
import com.jmethods.catatumbo.EntityManager;
import com.jmethods.catatumbo.EntityManagerFactory;
import com.jmethods.catatumbo.Identifier;

import lombok.Builder;
import lombok.Data;

@Data // Lombok
@Builder // Lombok
@Entity // Catatumbo
public class Car {
	@Identifier // Catatumbo
	private long id;

	private final String make;

	private final String model;

	private final int year;

	private String VIN;

	public static void main(String[] args) {
		EntityManager em = EntityManagerFactory.getInstance().createDefaultEntityManager();
		Car car = Car.builder().make("Mercedes").model("ML350").year(2011).VIN("11111111").build();
		Car car2 = em.insert(car);
		Car car3 = em.load(Car.class, car2.getId());
		System.out.println(car);
		System.out.println(car2);
		System.out.println(car3);
	}

}
```

**Comment by bnordli** [comment]
This looks great!

Will you support `setField(...)` methods on the builder in addition to Lombok's `field(...)`?

**Comment by athieriot** [comment]
By all means carry on with the release of the feature :)
It looks great as it is and will unlock the situation.

I think there is nothing, technically, that prevent us to implement the `with` feature in Catatumbo but I totally understand you want to limit the number of ways to use this feature.

I've been considering Lombok before but not sure how likely we are to use it. Might be a good time to propose again ;)
One question though, do you want to change the default `newBuilder` method to search for `builder` and be compatible with Lombok? (It's configurable anyway)

**Comment by sai-pullabhotla** [comment]
Search for the mutator methods in the Builder class is in the following **order**: 

- setField 
- withField
- field

Search for the static method that returns a Builder is in the following **order**: 

- newBuilder
- builder 

Let me know of any changes to this.

**Comment by athieriot** [comment]
Sounds perfect

**Comment by sai-pullabhotla** [comment]
@athieriot - the support for Builder pattern is merged into HEAD. Feel free to let me know if you need any further changes. Should have the release out over the weekend. Thanks.

**Comment by athieriot** [comment]
Hi !

Finally had the time to test it properly and I was wondering if there is a way to check for the `newBuilder` method the other way round?

Like: If there is a builder available use it, otherwise search for a Default constructor?

**Comment by sai-pullabhotla** [comment]
We could, but that may break backward compatibility on existing applications (assuming the persistence class is a classic POJO, but also has a `newBuilder` method. What is the rationale behind this change request? May be we need to introduce a new annotation - @Builder, if it is really needed?

**Comment by athieriot** [comment]
I know I've been prone to ask such requests before (Where it looks I try to "Pull the rug" to me) and it's actually quite good to have a defender of the library to keep it from side tracking :)

All in all, I just wanted to assure you that it's not out of laziness we are merely trying to protect the backward compatibility for our users as well.

I'll give a try today at using the new approach into our code base and see what happens. I might come back to you in the form of a Pull Request otherwise ;)

Thank you

**Pull request closed without merging**
